### ISSUE TITLE
Fermentrack losing pin assignment and iSpindel completely gone

### ISSUE THREAD

**Issue by mcinnes01** [thorrak/fermentrack#594] opened 2021-02-11 10:06 UTC
Hi

I'm on my second setup of fermentrack, the first used the standard automatic installer on a raspberry pi using raspbian and my latest setup is again using a pi and raspbian, but I have opted for the docker automatic installer.

On both setups I have experienced my brewpi pin assignments being lost periodically, however today I have also found my iSpindel has completely disappeared too.

So to describe my latest instance, 2 days ago I setup fermentrack running in docker on a fresh instance of raspbian running on a pi and I used the automatic installer to setup everything on the pi. I've not manually changed anything else on the pi other than setting the hostname and updating the corresponding hosts entry.

I then added my esp8266 (12e) for my fermenter controller, I decided to do a clean flash using the latest supported firmware. I mapped my pins and then moved my esp8266 back to in to my brewery (I'm using wifi and I have other esp devices close by that aren't having an issue with wifi signal although I'm not ruling out the cause as being a network drop).

I then configured my iSpindel and linked it to my fermenter brew-pi.

I'm not fermenting anything currently but wanted to check my setup for a couple of days before I brew this weekend, but today when I checked my dashboard I can see my iSpindel has gone completely and my esp8266 has lost it's pin assignment.

My iSpindel is switched off currently as I'm not using it, but the esp8266 has remained on. I'm not sure if it's like some network drop or fermentrack periodically polling to check the devices are online and then fermentrack removes the configuration if it can't find them or fermentrack isn't storing the configuration properly and is running from memory, but it seems to happen intermittently.

On my original fermentrack setup when I was just using it with an esp8266 to control my fermenter I had to reconfigure the pin assignment a number of times. Sometimes it runs for days without a hitch, other times an hour or so.

Is there any additional info I can provide to help identify the issue or is this something someone has observed before. I will say this is definitely not docker specific as I've had this same thing happen on both a native install and the docker install. Hopefully it's something simple and I can get it stable ready for my brew this weekend :)

NB I can see both the iSpindel and brewpi in the Django admin pages, so it seems like the iSpindel isn't displayed (perhaps as it's switched off?) on the dashboard and the brewpi has lost it's pin assignment somehow?

Here is the brewpi error log: [https://gist.github.com/mcinnes01/3827c3f78f2a16d3663987b1d63bd8d6](https://gist.github.com/mcinnes01/3827c3f78f2a16d3663987b1d63bd8d6)

Many thanks

Andy

**Comment by thorrak** [comment] 2021-02-11 13:52
What you're describing sounds like two different issues:

**Lost Pin Assignments**

To clarify an important point - **Fermentrack** doesn't keep track of pin assignments - they are written to memory on your temperature controller and tracked there. I mention this as I think we need to look at your controller to try to diagnose what is going on. From looking at the log you linked, there are two lines in particular that seem suspect:

> Feb 11 2021 00:06:43   Controller debug message: WARNING 2: Temperature sensor disconnected pin 0, address 28FF13F46E1404E2
> Feb 11 2021 00:06:43   Controller debug message: INFO MESSAGE 0: Temp sensor connected on pin 0, address 28FF13F46E1404E2  

That kind of connection/disconnection isn't normal and points to an issue either with the temperature sensors themselves, the controller itself, the power going to the temperature sensors, or the power going to the controller. 

Are you using a genuine (ie. direct from Lolin) D1 mini? How are you powering the controller? Are you using 5v or 3v to power the temperature sensors?


**iSpindel Disappearing**

This is very strange. Although there's logic to reset the temperature/gravity displayed if a device hasn't checked in recently, there isn't anything that would cause it to just disappear entirely. What specific URL path within Fermentrack (the bit after http://xxxx.local/) are you looking at?

**Comment by mcinnes01** [comment] 2021-02-11 14:47
Ah the pin disconnect could have genuinely been that, when I hooked it up to my fermenter I may have disconnected the temperature sensors to untangle the cables.

I use these a little ds18b20 breakout board and then have 2 more temperature probes soldered in parallel.

![temp-sensors](https://user-images.githubusercontent.com/877512/107650458-6ae0f300-6c76-11eb-8d2e-a70869386d9d.jpeg)

The temperature sensors are running on 3.3v and have been reporting temperatures accurately when it hasn't lost pin assignment.

I'm using a proper lolin device I think it's the espressiff dev kit c or something like that, I use them in other iot devices and they are solid. Power wise I've got it running on a 7W usb wall wort.

![brewpi](https://user-images.githubusercontent.com/877512/107650828-c6ab7c00-6c76-11eb-8713-2f268de1bea7.jpeg)

In regards to the iSpindel if I go to the root of the dashboard, then on the select device dropdown, I no longer see the iSpindel. On the dashboard I can see the linked hydrometer to the temperature controller and can browse to the hydrometer that way, but there is nothing there to control. Switching it back on doesn't seem to reconnect either as the temperature doesn't change from what it was last night when I configured it.

**Comment by mcinnes01** [comment] 2021-02-11 14:52
I have a reverse proxy setup to access fermentrack on a subdomain externally but I've ensured I've set the iSpindel up using the internal ip for the configuration so it's no going out and back in especially as at somepoint I probably need to lock that vlan down so it doesn't access the internet. mDNS worked absolutely without a hitch by the way :)

**Comment by thorrak** [comment] 2021-02-11 20:14
For what it's worth, that's not an official LOLIN board (or at least not a recent one) - but it's also not one of the ones that I've seen people come back and complain about. It's possible that the controller (or the flash on the controller) is an issue but that seems unlikely. 

I've never seen a setup like you have for the temperature sensors - what is "U1" on that breakout board you're using? 

To your question on the iSpindel: The iSpindels have fairly poor battery life when active, and therefore spend most of their life in sleep mode. I'm guessing what you're seeing is the fact that the iSpindel is only active on your network for a few seconds at a time - when you aren't presently watching it.

Considering all the above - it sounds like things are working as intended inside Fermentrack, though there does still appear to be some kind of issue with your controller/temperature sensors.

**Comment by mcinnes01** [comment] 2021-02-11 21:32
U1 is a DS18B20, I use that for room temp and then the cables you can see coming off it are to 2 other DS18B20s (one in the fermenter for beer temp and one in the glycol reservoir).

I've got a different esp8266 which I'm just flashing now and I've also got a spark photon somewhere I can try all failing.

I'll post back shortly after testing another device, and I'm going to leave the current brewpi on there to see if keeps its pin mapping.

I haven't used my iSpindel yet so I think it's probably just me, how often should they report?

**Comment by thorrak** [comment] 2021-02-11 22:12
> U1 is a DS18B20, I use that for room temp and then the cables you can see coming off it are to 2 other DS18B20s (one in the fermenter for beer temp and one in the glycol reservoir).
> 
> I've got a different esp8266 which I'm just flashing now and I've also got a spark photon somewhere I can try all failing.
> 
> I'll post back shortly after testing another device, and I'm going to leave the current brewpi on there to see if keeps its pin mapping.
> 
> I haven't used my iSpindel yet so I think it's probably just me, how often should they report?

That makes sense. You could also try powering the DS18b20s from 5v (leave data at 3v!) and see if that helps. It should - in theory - though I've had issues with some of mine where it actually caused them to stop responding (which makes absolutely no sense, but the overwhelming majority of these things that come in the "waterproof probe" style are counterfeit, so...)

**Comment by mcinnes01** [comment] 2021-02-12 14:50
Ok so I did have some other esp boards, but they are all esp32s or some dodgy esp8266s that just don't seem to work, even opened a brand new one and it just seemed flakey (different to the lolin style ones I'm currently using).

I couldn't see any options to run an esp32 as a temperature controller, but I do have a spark photon. I see your documentation says it's not currently supported but I wondered if there is something somewhere I could try with the spark? Reason I ask is that I I'm planning on installing my fermentation controller inside my chiller as I'll hard wire it in to control the recirculation pump and and I'll wire the heater cable I have wrapped around my fermenter in to the chiller power distribution board too. With the chiller being a metal box I'm not sure how great the wifi will be inside it, but with the spark photon I can mount an external aerial on the chiller case.

My current esp8266 lost it's pin assignment again over night, really not sure why it keeps doing that, I wonder though in general as a feature request maybe you can detect this for a configured device and perhaps store the pin mapping so you can push it back out if it loses it. Also storing a pin mapping "profile" would be cool if you already have your hardware configured in a set way and you just want to push the config back out i.e. if you need to replace your esp or whatever.

On the plus I can confirm my iSpindel is functioning as expected, didn't realise the update frequency was 15 minutes, so I think it was just a patience thing :) 

Many thanks

Andy

**Comment by thorrak** [comment] 2022-03-09 17:48
The issue for the loss of pin configuration seems to be related to some kind of security scan that certain routers perform. If the controller receives a message beginning with a capital `E` then it interprets that as a request to reset the EEPROM - this scan seems to be sending a message that fits that criteria.

I'm going to release firmware soon that adds a JSON confirmation requirement for EEPROM resets that should resolve this.

**Comment by thorrak** [comment] 2023-06-18 18:31
I believe this was closed in v15 of BrewPi-ESP8266 which is currently supported in the Dev branch of Fermentrack. Once that gets merged, this issue should be resolved. I’m going to tag that PR against this issue - if the issue reoccurs afterwards, let me know and we can revisit.

**Closed** 2023-06-23 23:24 UTC
Labels: Pending Pull
