### ISSUE TITLE
Fermentrack not communicating with script after upgrade. 

### ISSUE THREAD

**Issue by snoop6060** [thorrak/fermentrack#240] opened 2018-03-18 15:24 UTC
![48b18a4f-4c68-4982-adb0-8a5699a6f0b5](https://user-images.githubusercontent.com/36125121/37567537-561b8430-2ac0-11e8-9042-be0dadbd8492.jpeg)

Getting this after upgrade to latest version. Reboot didn't fix.

**Comment by snoop6060** [comment] 2018-03-18 21:25
Still getting this after pulling that latest commit. Do occasionally now see "starting script" but then goes back to the cannot recieve error as shown.

**Comment by thorrak** [comment] 2018-03-18 21:51
What do you have in your stderr log for that sensor?

To find it, click the question mark in the upper right hand corner, then click the stderr link in the table that shows up

**Comment by snoop6060** [comment] 2018-03-19 06:41
Mar 19 2018 06:38:54   Checking software version on controller... 
 Mar 19 2018 06:38:54   Found BrewPi v0.2.10 build unknown, running on an Arduino Uno with a revC shield on port /dev/ttyACM0

 Mar 19 2018 06:38:54   BrewPi version received was 0.2.10 which this script supports in 'legacy' branch mode.
 Mar 19 2018 06:38:54   Warning: version number of local copy of logMessages.h does not match log version number received from controller.controller version = 1, local copy version = 3. This is generally a non-issue, as thus far log messages have only been added - not changed.
 Mar 19 2018 06:38:54   Bound to TCP socket on port 2496, interface localhost 
 Mar 19 2018 06:38:54   Installed devices received: [{"a": "280DEE2805000075", "c": 1, "b": 0, "d": 0, "f": 5, "i": 0, "h": 2, "j": 0.0, "p": 18, "t": 1, "v": 21.313}, {"a": "28113728050000FE", "c": 1, "b": 1, "d": 0, "f": 9, "i": 1, "h": 2, "j": 0.0, "p": 18, "t": 1, "v": 23.5}, {"a": "285FAE28050000DC", "c": 1, "b": 0, "d": 0, "f": 6, "i": 2, "h": 2, "j": 0.0, "p": 18, "t": 1, "v": 13.875}, {"c": 1, "b": 0, "d": 0, "f": 2, "i": 3, "h": 1, "p": 5, "t": 3, "v": 0, "x": 1}, {"c": 1, "b": 0, "d": 0, "f": 3, "i": 4, "h": 1, "p": 6, "t": 3, "v": 0, "x": 1}]
 Mar 19 2018 06:38:54   Available devices received: [{"c": 1, "b": 0, "d": 0, "f": 0, "i": -1, "h": 1, "p": 2, "t": 0, "x": 1}, {"c": 1, "b": 0, "d": 0, "f": 0, "i": -1, "h": 1, "p": 19, "t": 0, "x": 1}, {"c": 1, "b": 0, "d": 0, "f": 0, "i": -1, "h": 1, "p": 4, "t": 0, "x": 1}]
Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/brewpi-script/brewpi.py", line 1008, in <module>
    util.save_beer_log_point(dbConfig, newRow)
  File "/home/fermentrack/fermentrack/brewpi-script/scriptlibs/BrewPiUtil.py", line 186, in save_beer_log_point
    new_log_point = models.BeerLogPoint()
NameError: global name 'models' is not defined
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/fermentrack/fermentrack/brewpi-script/scriptlibs/backgroundserial.py", line 108, in __listenThread
  File "/home/fermentrack/venv/local/lib/python2.7/site-packages/serial/serialutil.py", line 590, in inWaiting
  File "/home/fermentrack/venv/local/lib/python2.7/site-packages/serial/serialposix.py", line 467, in in_waiting
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'ioctl'
 Mar 19 2018 06:39:09   Connection type Serial selected. Opening serial port.
 Mar 19 2018 06:39:09   Connected via serial to port /dev/ttyACM0
 Mar 19 2018 06:39:09   Notification: Script started for beer 'Belgium saison'
 Mar 19 2018 06:39:19   Checking software version on controller... 
 Mar 19 2018 06:39:19   Found BrewPi v0.2.10 build unknown, running on an Arduino Uno with a revC shield on port /dev/ttyACM0

**Comment by Mikmonken** [comment] 2018-03-19 09:22
Building on this i get the python 3 message when i log into fermentrack so i run the curl script and it returns this.

pi@Fermentrack:~ $ curl -L install-python3.fermentrack.com | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131  100   131    0     0    281      0 --:--:-- --:--:-- --:--:--   281
100  7083  100  7083    0     0   8725      0 --:--:-- --:--:-- --:--:--  8725
::: This script was launched as root. Continuing installation.
::: Verifying free disk space...
::: Installing dependencies using apt-get
::: 'apt-key update' ran successfully.
::: apt is updated - installing git-core and build-essential.
::: (This may take a few minutes during which everything will be silent)



*** ERROR ERROR ERROR ERROR ERROR ***
----------------------------------
See above lines for error message
Setup NOT completed

[stderr fermentrack.txt](https://github.com/thorrak/fermentrack/files/1824333/stderr.fermentrack.txt)

for info i have upgraded to Stretch

**Comment by Mikmonken** [comment] 2018-03-19 09:22
and it's an RPI Zero (with wifi)

**Comment by Mikmonken** [comment] 2018-03-19 11:43
Quick update, after running sudo apt-get update and sudo apt-get upgrade, i mangaged to run the curl command and update to python 3. 

I get the template screen but that disappears after a reboot of the RPI which is good.

on the downside though still getting the Cannot receiveLCD text fromController/Script error.

[Fermentrack (Web Application) log-fermentrack-stderr.log .txt](https://github.com/thorrak/fermentrack/files/1824785/Fermentrack.Web.Application.log-fermentrack-stderr.log.txt)
[Process Spawner (BrewPi-Script, Tilt Daemon, etc.) log-fermentrack-processmgr.log.txt](https://github.com/thorrak/fermentrack/files/1824786/Process.Spawner.BrewPi-Script.Tilt.Daemon.etc.log-fermentrack-processmgr.log.txt)
[stderr - post python 3 update.txt](https://github.com/thorrak/fermentrack/files/1824787/stderr.-.post.python.3.update.txt)

**Comment by thorrak** [comment] 2018-03-19 11:53
@mikmonken - What do you get when you run:

`ps -xauf | grep fermentrack`

It’s strange, because the errror you’re getting makes it sound like the issue is loading the models (which makes no sense - as long as it’s running in the virtualenv)

**Comment by Mikmonken** [comment] 2018-03-19 11:55
pi@Fermentrack:~ $ ps -xauf | grep fermentrack
ferment+  1240  0.0  0.2   1892  1076 ?        Ss   11:20   0:00      \_ /bin/sh -c ~/fermentrack/brewpi-script/utils/updateCronCircus.sh startifstopped
ferment+  1241  0.0  0.4   4616  1824 ?        S    11:20   0:00          \_ /bin/bash /home/fermentrack/fermentrack/brewpi-script/utils/updateCronCircus.sh startifstopped
ferment+  1242  0.2  4.4  43316 19880 ?        Sl   11:20   0:05              \_ /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/circusctl status
pi        1809  0.0  0.4   4364  1968 pts/0    S+   11:54   0:00              \_ grep --color=auto fermentrack
ferment+   900  0.8  3.4  44592 15464 ?        Sl   11:07   0:24 /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/circusd --daemon /home/fermentrack/fermentrack/circus.ini
ferment+   913  1.8 11.7  85472 52184 ?        Ss   11:07   0:52  \_ /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/chaussette --fd 9 fermentrac_django.wsgi:application
ferment+   914  1.6 11.6  85096 51592 ?        Ss   11:07   0:46  \_ /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/chaussette --fd 9 fermentrac_django.wsgi:application
ferment+   915  1.4 10.7  91028 47604 ?        Ssl  11:07   0:41  \_ /home/fermentrack/venv/bin/python /home/fermentrack/fermentrack/manage.py run_huey
ferment+   916  1.0  9.1  66172 40480 ?        Ssl  11:07   0:29  \_ /home/fermentrack/venv/bin/python /home/fermentrack/fermentrack/utils/processmgr.py
ferment+   917 18.8  4.4  44084 19668 ?        Ssl  11:07   8:46  \_ /home/fermentrack/venv/bin/python3 -c from circus import stats; stats.main() --endpoint tcp://127.0.0.1:5555 --pubsub tcp://127.0.0.1:5556 --statspoint tcp://127.0.0.1:5557 --log-level ERROR --log-output /home/fermentrack/fermentrack/log/circusd.log
ferment+  1774 60.8  9.1  48956 40876 ?        Ss   11:53   0:20  \_ python -u /home/fermentrack/fermentrack/brewpi-script/brewpi.py --dbcfg Old Larry

**Comment by Mikmonken** [comment] 2018-03-19 11:57
It's an issue i had previously though with a different ESP, it actually resulted in me moving from wifi to serial (well that and the fact both the RPI Zero W and esp board fit well in the box)

**Comment by Mikmonken** [comment] 2018-03-19 12:07
could it be related to this a very old version of the same problem linked to python, (new browser based or rotating though? 

https://community.brewpi.com/t/cannot-receive-lcd-text-from-python-script/1616

**Comment by thorrak** [comment] 2018-03-19 12:10
I think this is actually the result of another bug - one that I had hidden because BrewPi-script was designed (initially) to work with both Fermentrack and BrewPi-www. Now that everything is Python 3, that doesn’t make sense any more.

I’ve removed the code that hides the error but I still expect something to break. If you don’t mind testing it, can you log into your Pi, change to the Fermentrack user, and then run:

`~/fermentrack/utils/upgrade3.sh -b mikmonken`

That should switch to a branch that has a quick attempt at a patch. If I can get that branch working we should be in business.

Sent from my iPhone

On Mar 19, 2018, at 7:57 AM, Mikmonken <notifications@github.com<mailto:notifications@github.com>> wrote:


It's an issue i had previously though with a different ESP, it actually resulted in me moving from wifi to serial (well that and the fact both the RPI Zero W and esp board fit well in the box)

**Comment by Mikmonken** [comment] 2018-03-19 12:23
strike that got it. just running update now

**Comment by Mikmonken** [comment] 2018-03-19 12:35
I got a permission denied line when running the command but it seemed to update OK.

pi@Fermentrack:~ $ sudo su
root@Fermentrack:/home/pi# su fermentrack
fermentrack@Fermentrack:/home/pi$ ~/fermentrack/utils/upgrade3.sh -b mikmonken
tee: upgrade.log: Permission denied
::: Triggering upgrade from branch mikmonken
::: Waiting 2 seconds for Fermentrack to send updates if triggered from the web...
::: Stopping circus...
/home/fermentrack/fermentrack/utils/upgrade3.sh: line 87: upgrade.log: Permission denied
::: Updating from git...
::: Updating requirements via pip...
::: Running manage.py migrate...
::: Running manage.py collectstatic...
::: Relaunching circus...
::: Complete!
fermentrack@Fermentrack:/home/pi$ 

Issue is still there though

pi@Fermentrack:~ $ ps -xauf | grep fermentrack
pi        1130  0.0  0.4   4364  1888 pts/0    S+   12:34   0:00              \_ grep --color=auto fermentrack
ferment+   847  1.1  3.9  44464 17668 ?        Sl   12:31   0:01 /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/circusd --daemon /home/fermentrack/fermentrack/circus.ini
ferment+   893 16.7 11.7  75104 52100 ?        Ss   12:31   0:27  \_ /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/chaussette --fd 9 fermentrac_django.wsgi:application
ferment+   896 16.8 11.7  74844 52132 ?        Ss   12:31   0:27  \_ /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/chaussette --fd 9 fermentrac_django.wsgi:application
ferment+   897 15.4 11.0  91028 48948 ?        Ssl  12:31   0:24  \_ /home/fermentrack/venv/bin/python /home/fermentrack/fermentrack/manage.py run_huey
ferment+   898 12.7  9.1  65656 40668 ?        Ssl  12:31   0:20  \_ /home/fermentrack/venv/bin/python /home/fermentrack/fermentrack/utils/processmgr.py
ferment+   901 17.0  4.5  43808 20332 ?        Rsl  12:31   0:27  \_ /home/fermentrack/venv/bin/python3 -c from circus import stats; stats.main() --endpoint tcp://127.0.0.1:5555 --pubsub tcp://127.0.0.1:5556 --statspoint tcp://127.0.0.1:5557 --log-level ERROR --log-output /home/fermentrack/fermentrack/log/circusd.log

**Comment by thorrak** [comment] 2018-03-19 14:16
What do you see in that controller’s stderr log?

Sent from my iPhone

On Mar 19, 2018, at 8:35 AM, Mikmonken <notifications@github.com<mailto:notifications@github.com>> wrote:


I got a permission denied line when running the command but it seemed to update OK.

pi@Fermentrack:~ $ sudo su
root@Fermentrack:/home/pi# su fermentrack
fermentrack@Fermentrack:/home/pi$ ~/fermentrack/utils/upgrade3.sh -b mikmonken
tee: upgrade.log: Permission denied
::: Triggering upgrade from branch mikmonken
::: Waiting 2 seconds for Fermentrack to send updates if triggered from the web...
::: Stopping circus...
/home/fermentrack/fermentrack/utils/upgrade3.sh: line 87: upgrade.log: Permission denied
::: Updating from git...
::: Updating requirements via pip...
::: Running manage.py migrate...
::: Running manage.py collectstatic...
::: Relaunching circus...
::: Complete!
fermentrack@Fermentrack:/home/pi$

Issue is still there though

pi@Fermentrack:~ $ ps -xauf | grep fermentrack
pi 1130 0.0 0.4 4364 1888 pts/0 S+ 12:34 0:00 _ grep --color=auto fermentrack
ferment+ 847 1.1 3.9 44464 17668 ? Sl 12:31 0:01 /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/circusd --daemon /home/fermentrack/fermentrack/circus.ini
ferment+ 893 16.7 11.7 75104 52100 ? Ss 12:31 0:27 _ /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/chaussette --fd 9 fermentrac_django.wsgi:application
ferment+ 896 16.8 11.7 74844 52132 ? Ss 12:31 0:27 _ /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/bin/chaussette --fd 9 fermentrac_django.wsgi:application
ferment+ 897 15.4 11.0 91028 48948 ? Ssl 12:31 0:24 _ /home/fermentrack/venv/bin/python /home/fermentrack/fermentrack/manage.py run_huey
ferment+ 898 12.7 9.1 65656 40668 ? Ssl 12:31 0:20 _ /home/fermentrack/venv/bin/python /home/fermentrack/fermentrack/utils/processmgr.py
ferment+ 901 17.0 4.5 43808 20332 ? Rsl 12:31 0:27 _ /home/fermentrack/venv/bin/python3 -c from circus import stats; stats.main() --endpoint tcp://127.0.0.1:5555 --pubsub tcp://127.0.0.1:5556 --statspoint tcp://127.0.0.1:5557 --log-level ERROR --log-output /home/fermentrack/fermentrack/log/circusd.log

**Comment by Mikmonken** [comment] 2018-03-19 14:22
think this is the right log.

    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'fermentrack_django'
Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/brewpi-script/brewpi.py", line 21, in <module>
    from scriptlibs.BrewPiUtil import printStdErr, logMessage, asciiToUnicode
  File "/home/fermentrack/fermentrack/brewpi-script/scriptlibs/BrewPiUtil.py", line 37, in <module>
    application = get_wsgi_application()
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'fermentrack_django'
Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/brewpi-script/brewpi.py", line 21, in <module>
    from scriptlibs.BrewPiUtil import printStdErr, logMessage, asciiToUnicode
  File "/home/fermentrack/fermentrack/brewpi-script/scriptlibs/BrewPiUtil.py", line 37, in <module>
    application = get_wsgi_application()
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'fermentrack_django'
Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/brewpi-script/brewpi.py", line 21, in <module>
    from scriptlibs.BrewPiUtil import printStdErr, logMessage, asciiToUnicode
  File "/home/fermentrack/fermentrack/brewpi-script/scriptlibs/BrewPiUtil.py", line 37, in <module>
    application = get_wsgi_application()
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'fermentrack_django'
Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/brewpi-script/brewpi.py", line 21, in <module>
    from scriptlibs.BrewPiUtil import printStdErr, logMessage, asciiToUnicode
  File "/home/fermentrack/fermentrack/brewpi-script/scriptlibs/BrewPiUtil.py", line 37, in <module>
    application = get_wsgi_application()
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'fermentrack_django'
Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/brewpi-script/brewpi.py", line 21, in <module>
    from scriptlibs.BrewPiUtil import printStdErr, logMessage, asciiToUnicode
  File "/home/fermentrack/fermentrack/brewpi-script/scriptlibs/BrewPiUtil.py", line 37, in <module>
    application = get_wsgi_application()
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'fermentrack_django'

**Comment by Mikmonken** [comment] 2018-03-19 14:29
when i go onto the debug device connection it now says this.


Test | Parameter | Pass/Fail | Output
-- | -- | -- | --
Device Status Test | active | Passed | Device active & managed by Circus
Udev Availability Test | linux | Failed | pyudev is not available, or isn't loaded

which is different to the test outcome that i had the other day.

[img]https://www.homebrewtalk.com/forum/attachments/img_2584-jpg.562558/ [/img]

**Comment by Mikmonken** [comment] 2018-03-19 15:46
also just having a look around am now getting an error when trying to reach the constance config page.

> 

Request Method: | GET
-- | --
http://fermentrack.local/admin/constance/config/
1.11.11
AttributeError
'str' object has no attribute 'utcoffset'
/home/fermentrack/venv/lib/python3.5/site-packages/django/utils/timezone.py in is_aware, line 261
/home/fermentrack/venv/bin/python3
3.5.3
['/home/fermentrack/venv/lib/python3.5/site-packages/git/ext/gitdb',  '/home/fermentrack/venv/bin',  '/home/fermentrack/fermentrack',  '/home/fermentrack/venv/lib/python3.5/site-packages',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-arm-linux-gnueabihf',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages',  '.',  '/home/fermentrack/venv/lib/python3.5/site-packages/gitdb/ext/smmap']
Mon, 19 Mar 2018 15:44:49 +0000

**Comment by thorrak** [comment] 2018-03-20 04:14
I just pushed live a commit which should fix both the Constance issue as well as the unresponsive controller issue. Let me know if you have any other problems - otherwise I'll close this issue out later this week.

**Comment by snoop6060** [comment] 2018-03-20 05:45
Fixed for me, cheers :)

**Comment by Mikmonken** [comment] 2018-03-20 14:20
Mine now fixed too thanks.

**Closed** 2018-03-22 11:48 UTC

**Comment by brewskies393** [comment] 2019-01-11 02:38
I am having this exact same issue after about 18-24 hours of use on a new load of Fermentrack. I am at the latest commit, (24 Oct 2018). Getting either a "script starting up" or a "Cannot receive LCD text from Controller/Script" in my status window, not sure what makes it do one vs the other. All Temp probes read None F. Any Thoughts? stderr logs below.

[log uno stderr log.txt](https://github.com/thorrak/fermentrack/files/2747853/log.uno.stderr.log.txt)
[log fermentrack stderr log.txt](https://github.com/thorrak/fermentrack/files/2747855/log.fermentrack.stderr.log.txt)

**Comment by l30ns** [comment] 2020-09-19 16:35
Hi, I have the same issue repeating after the update in September 16, 2020.
What was the fix earlier? Should I just reinstall the Fermentrack?
