### ISSUE TITLE
Is it possible to trigger temp changes when certain attenuation is reached?

### ISSUE THREAD

**Issue by Plastic1982** [thorrak/fermentrack#488] opened 2020-08-01 04:41 UTC
I have a Tilt connected to Fermentrack via a Tilt Bridge. Is there a way to get the temperature controller to change temperatures of a fermentation once a certain attenuation is reached? For example, I would like to set it up so the controller raises the temp as the end of the fermentation approaches (as calculated by attenuation via the Tilt) and then cold crashes once terminal gravity has been reached (ie, the Tilt measures the same gravity for 48-72 hours straight)

**Comment by lbussy** [comment] 2020-08-01 18:09
Duplicate of #287.

**Comment by thorrak** [comment] 2023-06-20 05:39
Closing this since - as @lbussy noted - it is a duplicate of #287

**Closed by thorrak** 2023-06-20 05:39 UTC
Labels: duplicate
